name: flutter_useful_widgets
description: 一些实用组件.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  
  just_the_tooltip: ^0.0.12 # date_picker
  calendar_date_picker2: ^0.3.5 # date_picker

  screenshot: ^1.3.0 # image_editor
  flutter_painting_tools: ^1.3.0 # image_editor
  provider: ^6.0.5 # image_editor


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
